from dotenv import load_dotenv
import os

SQLALCHEMY_DATABASE_URI_DEV = os.getenv('SQLALCHEMY_DATABASE_URI_DEV')
SQLALCHEMY_DATABASE_URI_PROD = os.getenv('SQLALCHEMY_DATABASE_URI_PROD')

class Config:
    SQLALCHEMY_TRACK_MODIFICATIONS = False

class DevConfig(Config):
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI_DEV

class ProdConfig(Config):
    DEBUG = False
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI_PROD
